name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Run compilation inside Docker container
      run: docker run myapp sh ../../../compile-with-docker.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: compiled-firmware
        path: compiled-files  # Replace with the path to your compiled files
